### PR TITLE
Mac builds for new releases

### PR DESCRIPTION
**Pull request by noamross**

### CODE REVIEW

**Comment by jankatins** [comment]
Nice thanks! To remove the old commits with the old packages from the repo, can you squash down (`git pull origin; git rebase -i origin/master` and then basically replace all first words with "s" and then re-edit the commit message)? Afterwards there should be only one commit with only the added packages (the gitignore change is already in the repo :-) ) and a `git push -f` will push the replaced branch/commit to this PR.

That way, the packages for the old version won't be in this repo and therefore won't blow up the repo size.

**Comment by takluyver** [comment]
I think you have to leave the first word on the first line alone, and replace the rest with 's' - there needs to be at least one commit for the others to squash into. And after rebasing, you'll need to push with a `-f` flag to make it accept the changes. If you're not that comfortable with git, then just copy the `macosx` directory, make a new branch off `origin/master`, commit the new files again and make a new PR.

**Comment by jankatins** [comment]
LGTM (just looking at the commits, not testing the packages...).

If you squash both commits, the DS_store would go away too, but IMO that's not so bad as the old packages.

Thanks!

**Comment by takluyver** [comment]
Thanks @noamross

**Pull request merged**
