### PR TITLE
IRkernel v0.4 f12dfa057b13574a57721b25154e36563401c90b

### PR DESCRIPTION
**Pull request by jankatins**
Based on this commit in IRkernel:

commit f12dfa057b13574a57721b25154e36563401c90b
Author: Thomas Kluyver takowl@gmail.com
Date:   Mon Jun 1 10:42:47 2015 -0700

```
Bump version number to 0.4
```

see also: https://github.com/IRkernel/IRkernel/issues/144

### CODE REVIEW

**Comment by jankatins** [comment]
@noamross: can you build for mac? Please ensure that the mac packages end up in the 'mavericks' subdir... Not sure how @flying-sheep did that the last time...

**Comment by takluyver** [comment]
Thanks! Since this is a pure R package (no compiled parts), is there an easy way to make the OS X binary package without OS X?

**Comment by takluyver** [comment]
Oh, I guess that means there isn't.

**Comment by flying-sheep** [comment]
i created the directory and moved them manually…

**Comment by takluyver** [comment]
Oops, I thought I had merged this.

**Comment by noamross** [comment]
Sorry I've been MIA!  Do you still need this?

**Comment by takluyver** [comment]
No problem! No-one else has built them. I'm not entirely sure whether binary packages are needed for code without any compiled parts, but if they are, it would be great if you could build them again. :-)

**Pull request merged**
