### PR TITLE
Repr 0.2

### PR DESCRIPTION
**Pull request by jankatins**
This adds the source packages for repr 0.2. 

It also adds the macosx binary packages for repr 0.2 and irkernel 0.4 (the same packages as in #14 / #11, just moved around). I also put the macosx packages in the same subdir structure as on cran (see here: http://cran.r-project.org/bin/macosx/mavericks/contrib/). The old dir structure didn't work on Mac OSX.

It also adds the Windows binary packages for repr 0.2.

I also added a document which explains what I do when I add new releases (I currently use R's internal PACKAGE building function directly and not drat). I also added what I think is the macosx version of that code, but this is obviously untested... @noamross If you can build the repr packages, it would be nice if you could check the instructions... Thanks :-)

Closes: #12
Closes: #11 
Closes: #14 

Thanks to @noamross for the Mac OSX binaries!

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks. Waiting for an OS X user who can test this.

**Comment by jankatins** [comment]
Ok, I tested it on a mac os x laptop:

```
install.packages(c('rzmq','repr','IRkernel','IRdisplay'), repos = c('http://irkernel.github.io/', getOption('repos')))
Warning in install.packages :
 Öffnen fehlgeschlagen: HTTP Status war '404 Not Found'
Warning in install.packages :
 Öffnen fehlgeschlagen: HTTP Status war '404 Not Found'
Warning in install.packages :
 unable to access index for repository http://irkernel.github.io/bin/macosx/mavericks/contrib/3.1

  packages ‘repr’, ‘IRkernel’, ‘IRdisplay’ are available as source packages but not as binaries

Warning in install.packages :
 packages ‘repr’, ‘IRkernel’, ‘IRdisplay’ are not available (as a binary package for R version 3.1.3)
versuche URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/rzmq_0.7.7.tgz'
Content type 'application/x-gzip' length 2189357 bytes (2.1 MB)
URL geöffnet
==================================================
downloaded 2.1 MB


The downloaded binary packages are in
/var/folders/rg/yfn1k01x2fb9gpwy6m6pvlc40000gn/T//RtmpwKQNLn/downloaded_packages
```

**Comment by jankatins** [comment]
This should IMO be ready for merging. I will test it afterwards that it installs on the above Mac OSX system.

**Comment by takluyver** [comment]
Thanks, merging.

**Comment by jankatins** [comment]
Just for the reference:

```
> install.packages(c('rzmq','repr','IRkernel','IRdisplay'), repos = c('http://irkernel.github.io/', getOption('repos')))

also installing the dependencies ‘evaluate’, ‘jsonlite’, ‘uuid’, ‘base64enc’

versuche URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/evaluate_0.7.tgz'
Content type 'application/x-gzip' length 34791 bytes (33 KB)
URL geöffnet
==================================================
downloaded 33 KB

versuche URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/jsonlite_0.9.16.tgz'
Content type 'application/x-gzip' length 974834 bytes (951 KB)
URL geöffnet
==================================================
downloaded 951 KB

versuche URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/uuid_0.1-1.tgz'
Content type 'application/x-gzip' length 24550 bytes (23 KB)
URL geöffnet
==================================================
downloaded 23 KB

versuche URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/base64enc_0.1-2.tgz'
Content type 'application/x-gzip' length 22654 bytes (22 KB)
URL geöffnet
==================================================
downloaded 22 KB

versuche URL 'http://irkernel.github.io/bin/macosx/mavericks/contrib/3.1/rzmq_0.7.7.tgz'
Content type 'application/octet-stream' length 81794 bytes (79 KB)
URL geöffnet
==================================================
downloaded 79 KB

versuche URL 'http://irkernel.github.io/bin/macosx/mavericks/contrib/3.1/repr_0.2.tgz'
Content type 'application/octet-stream' length 15740 bytes (15 KB)
URL geöffnet
==================================================
downloaded 15 KB

versuche URL 'http://irkernel.github.io/bin/macosx/mavericks/contrib/3.1/IRkernel_0.4.tgz'
Content type 'application/octet-stream' length 60683 bytes (59 KB)
URL geöffnet
==================================================
downloaded 59 KB

versuche URL 'http://irkernel.github.io/bin/macosx/mavericks/contrib/3.1/IRdisplay_0.3.tgz'
Content type 'application/octet-stream' length 21264 bytes (20 KB)
URL geöffnet
```

-> it works!

**Comment by takluyver** [comment]
:-)

**Pull request merged**
